### ISSUE TITLE
Add Django contexts and Django Renderer

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/exceptionite#27]
Just need to add Django contexts that are on the current Django exception page. This will put it at feature parity with the current exception screen
<img width="391" alt="Screen Shot 2022-04-14 at 6 03 39 PM" src="https://user-images.githubusercontent.com/20172538/163483821-09658c0f-7a04-4a18-bb1c-418d08a2ea56.png">
<img width="373" alt="Screen Shot 2022-04-14 at 6 03 33 PM" src="https://user-images.githubusercontent.com/20172538/163483822-d345b9af-c3a9-4e42-a649-f2e1bda93c39.png">
<img width="370" alt="Screen Shot 2022-04-14 at 6 03 23 PM" src="https://user-images.githubusercontent.com/20172538/163483824-11dfb474-43c3-4d79-a34d-ff8201dcdf54.png">
<img width="361" alt="Screen Shot 2022-04-14 at 6 03 17 PM" src="https://user-images.githubusercontent.com/20172538/163483825-71896b22-2a8a-4d73-a260-8201beeecb5c.png">
<img width="430" alt="Screen Shot 2022-04-14 at 6 03 10 PM" src="https://user-images.githubusercontent.com/20172538/163483829-5ed81bb6-2772-4214-95db-cdfa75a45deb.png">
<img width="428" alt="Screen Shot 2022-04-14 at 6 03 02 PM" src="https://user-images.githubusercontent.com/20172538/163483833-e28169df-d4d8-442d-9798-7e9bbfd55001.png">
<img width="431" alt="Screen Shot 2022-04-14 at 6 02 54 PM" src="https://user-images.githubusercontent.com/20172538/163483834-98e1fcc7-7f3c-4dfc-a392-c3b975085618.png">

**Comment by girardinsamuel** [comment]
How to fetch those variables and context is detailed here
https://github.com/django/django/blob/b1005c0e4029c23f4e718ce0a7afdfa926c095de/django/views/debug.py#L356

It would be good to create different blocks for this, or one block with sections 😉 (has_sections = True in the block)
https://github.com/MasoniteFramework/exceptionite/#block
