### ISSUE TITLE
Add better team debugging support

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/exceptionite#3]
There should be a way we can add some kind of team debugging .. Anytime someone has an issue in Slack or something they usually hit this page. So if there was a string or something they could give which could help us debug then that would be super useful.

Thinking they give us a string like:
```
dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7dhiusdb79837rt4t64nyct4t478jty84fy8w7y7
```

Then we put it in a searchbox in our app and then we can see the full stack trace or something .. not sure if this is useless or if there is a better way to achieve the goal

**Comment by Marlysson** [comment]
```Then we put it in a searchbox in our app and then we can see the full stack trace or something```

Do other instances of masonite see other stack traces from another installation in other notebooks, computers? Should have some way to connect these instances, don't?

**Comment by josephmancuso** [comment]
i'm not sure. I am thinking of ways to improve debugging between people .. This might not even be the best approach

**Comment by Marlysson** [comment]
Maybe some service like Lavavel does... Some way to store the environment of current trackback on the server ( maybe this is overdone just to "some json data" ) and when put this hash, to recover the current stack trace ... Maybe the ideal would be a piece of code + stack trace ( just ideas 😄 )

**Comment by josephmancuso** [comment]
I'm not sure we need this anymore.

* The solution to this should be using the new exception sharing 
* or just saving the page and sharing the .html file
