### ISSUE TITLE
Add instructions for registering Django 404 exception page

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/exceptionite#35]
Probably as simple as just hooking into another exception handler

**Comment by girardinsamuel** [comment]
It's a bit more complex actually:
https://github.com/django/django/blob/main/django/core/handlers/exception.py#L65

There is a specific handler that is not configurable when in debug mode. The only might be to patch this.

And that makes me think, we need to check that when debug=False, if exceptionite page is still showing up or not !! ⚠️
