### ISSUE TITLE
Add more details for exception

### ISSUE THREAD

**Issue by flowercoder** [MasoniteFramework/exceptionite#47]
I try this exception library yesterday，I have some trouble right now.
I need to use request method to visit some website. I try this library, it only show one line error information about it if my visit does not work. I need specific exceptions about it. So please add a optional in this case.
In addition, i try to “Adding Context” by the homepage example. I follow it, but it does not work. I don`t know why. So please offer more example about this library. Thanks a lot.

**Comment by josephmancuso** [comment]
I will need more information for this issue.

* Can you provide code examples? 
* Can you provide what you have tried? 
* Can you provide screenshots or code examples of whats not working?

**Comment by girardinsamuel** [comment]
@flowercoder I don't know if you have seen the comment above 😉 ?

**Comment by flowercoder** [comment]
> @flowercoder I don't know if you have seen the comment above 😉 ?

Sorry, I just saw it. Right now I mean I have no idea that my issue is really issue or not. Cause that I use the request method, the response back the 405 code, I just  realized that i cannot look at the response code as error information.

**Comment by girardinsamuel** [comment]
@flowercoder
As Joe was saying we will need a bit more info to help you on this:

- What framework are you using ? Masonite, Flask, Django ?
- Can you provide code examples ?

And if you can:
- Can you provide what you have tried?
- Can you provide screenshots or code examples of whats not working?

**Comment by girardinsamuel** [comment]
Using `requests` python module does not raise an exception if the returned server response has an error. The response will be an error response with an error status code.

`exceptionite` display information about the error based on an exception. Here no exception is raised, so you `exceptionite` can't help you. What you should do is to "analyze"/"parse" the response object to find the status code, the error message...
```python
url = "https://www.google.com"
    headers = {
                'Accept': 'application/json, text/plain, */*',
                'X-Signature': '',
                'X-Service-Method': 'getVerifyCodeInfo',
                'X-Access-Token': 'null',
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
                'X-Service-Id': 'cas-web.smsService',
                'Content-Type': 'application/json',
                'host': 'e-hospital.jshtcm.com'
            }
    response = requests.post(url, headers)
    code = response.status_code
    error_content = response.text
    # maybe if it's an api it's easier to parse the response as json if the server handles it
    error_content = response.json()
```

If you really want to use exceptionite you should parse the error response from `requests` module and then raise an exception with the info and handles it with `exceptionite`. It would look like:
```python
import requests
# ...
response = requests.post(url, headers)
if response.status_code >= 400:
    # an error happened
    # analyze content
    error = response.json()
    error_title = ...
    message = f"Error {response.status_code} - {error_title}"
    exception = CustomException(message)
    handler = Handler()
    handler.start(exception)
    handler.render("terminal")
else:
    # continue normally...
```

But I am not sure `exceptionite` is very useful here.

**Comment by girardinsamuel** [comment]
I am closing this issue as we clarified how to use exceptionite in this case even if it has not really been made for this use case. 😉
